version: '3.8'

services:
  compiler:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    command: cargo test
    environment:
      - RUST_BACKTRACE=1

  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    command: cargo run -- --help
    environment:
      - RUST_BACKTRACE=1

  wasm-test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    command: cargo test --test integration_tests
    environment:
      - RUST_BACKTRACE=1 

  run-test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    command: cargo run -- test.cln
    environment:
      - RUST_BACKTRACE=1 