name: Release Clean Language Compiler

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag'
        required: true
        default: 'v0.1.0'

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            name: cln-linux-x86_64
            archive: tar.gz
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
            name: cln-linux-aarch64
            archive: tar.gz
          - target: x86_64-apple-darwin
            os: macos-latest
            name: cln-macos-x86_64
            archive: tar.gz
          - target: aarch64-apple-darwin
            os: macos-latest
            name: cln-macos-aarch64
            archive: tar.gz
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            name: cln-windows-x86_64
            archive: zip

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}

    - name: Install cross-compilation tools (Linux ARM64)
      if: matrix.target == 'aarch64-unknown-linux-gnu'
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu

    - name: Configure cross-compilation (Linux ARM64)
      if: matrix.target == 'aarch64-unknown-linux-gnu'
      run: |
        mkdir -p ~/.cargo
        echo '[target.aarch64-unknown-linux-gnu]' >> ~/.cargo/config.toml
        echo 'linker = "aarch64-linux-gnu-gcc"' >> ~/.cargo/config.toml

    - name: Build binary
      run: cargo build --release --bin cln --target ${{ matrix.target }}

    - name: Strip binary (Unix)
      if: matrix.os != 'windows-latest' && matrix.target != 'aarch64-unknown-linux-gnu'
      run: strip target/${{ matrix.target }}/release/cln || true

    - name: Strip binary (Linux ARM64)
      if: matrix.target == 'aarch64-unknown-linux-gnu'
      run: aarch64-linux-gnu-strip target/${{ matrix.target }}/release/cln || true

    - name: Create archive (Unix)
      if: matrix.os != 'windows-latest'
      run: |
        cd target/${{ matrix.target }}/release
        tar -czf ../../../${{ matrix.name }}.tar.gz cln
        cd -

    - name: Create archive (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        cd target/${{ matrix.target }}/release
        7z a ../../../${{ matrix.name }}.zip cln.exe
        cd -

    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.name }}
        path: ${{ matrix.name }}.${{ matrix.archive }}

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Move artifacts to root
      run: |
        find artifacts -name "*.tar.gz" -o -name "*.zip" | while read file; do
          mv "$file" .
        done
        ls -la *.tar.gz *.zip

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          *.tar.gz
          *.zip
        body: |
          ## Clean Language Compiler ${{ github.ref_name }}
          
          **Author:** Ivan Pasco Lizarraga  
          **Website:** https://www.cleanlanguage.dev  
          
          Pre-built binaries for the Clean Language compiler.
          
          ### Installation
          
          Download the appropriate binary for your platform and add it to your PATH.
          
          ### Platforms
          
          - **Linux x86_64**: `cln-linux-x86_64.tar.gz`
          - **Linux ARM64**: `cln-linux-aarch64.tar.gz`
          - **macOS x86_64**: `cln-macos-x86_64.tar.gz`
          - **macOS ARM64**: `cln-macos-aarch64.tar.gz`
          - **Windows x86_64**: `cln-windows-x86_64.zip`
          
          ### Usage
          
          ```bash
          # Compile a Clean Language file
          cln compile hello.cln
          
          # Run a Clean Language program
          cln run hello.cln
          
          # Check version
          cln version
          ```
          
          For more information, visit: https://www.cleanlanguage.dev
        draft: false
        prerelease: false 